package com.devianwahyu.books.model

import com.devianwahyu.books.R

object BookData {

    private val dataBooks = arrayOf(
        arrayOf("Harry Potter", "J.K Rowling", "2005", "Harry Potter adalah seri tujuh novel fantasi yang dikarang oleh penulis Inggris J. K. Rowling. Novel ini mengisahkan tentang petualangan seorang penyihir remaja bernama Harry Potter dan sahabatnya, Ronald Bilius Weasley dan Hermione Jean Granger, yang merupakan pelajar di Sekolah Sihir Hogwarts. Inti cerita dalam novel-novel ini berpusat pada upaya Harry untuk mengalahkan penyihir hitam jahat bernama Lord Voldemort, yang berambisi untuk menjadi makhluk abadi, menaklukkan dunia sihir, menguasai orang-orang nonpenyihir, dan membinasakan siapapun yang menghalangi jalannya, terutama Harry Potter.", R.drawable.harry_potter_cover),
        arrayOf("Impact of AI", "Log Melin", "2018", "Kecerdasan buatan adalah kecerdasan yang ditambahkan kepada suatu sistem yang bisa diatur dalam konteks ilmiah atau bisa disebut juga intelegensi artifisial (bahasa Inggris: Artificial Intelligence) atau hanya disingkat AI, didefinisikan sebagai kecerdasan entitas ilmiah. Andreas Kaplan dan Michael Haenlein mendefinisikan kecerdasan buatan sebagai “kemampuan sistem untuk menafsirkan data eksternal dengan benar, untuk belajar dari data tersebut, dan menggunakan pembelajaran tersebut guna mencapai tujuan dan tugas tertentu melalui adaptasi yang fleksibel”.[1] Sistem seperti ini umumnya dianggap komputer. Kecerdasan diciptakan dan dimasukkan ke dalam suatu mesin (komputer) agar dapat melakukan pekerjaan seperti yang dapat dilakukan manusia. Beberapa macam bidang yang menggunakan kecerdasan buatan antara lain sistem pakar, permainan komputer (games), logika fuzzy, jaringan saraf tiruan dan robotika.", R.drawable.ai_cover),
        arrayOf("Blott", "Daniel Parsons", "2010", "Sir Giles Lynchwood was played by George Cole, with Geraldine James as Lady Maud, Julia McKenzie as Mrs Forthby, David Suchet as Blott, Paul Brooke as Mr Hoskins, Clare Grogan as the receptionist at the Handyman Arms hotel, Simon Cadell as Mr Dundridge, Geoffrey Chater as the Government Minister, Jeremy Clyde as his private secretary Densher and Geoffrey Bayldon as local solicitor Mr Ganglion.", R.drawable.blott_cover),
        arrayOf("24 Hour Rule", "Charles Fred", "2017", "Handyman Hall was filmed at Stanage Park, near Heartsease, Powys, a few miles west of Ludlow. The town of Ludlow stood in for the fictitious town of Worford, with a number of pubs and other buildings used there, though the Town Hall used as the courthouse was demolished in 1986.[2] Deddington in Oxfordshire was the filming location for the village of Guildstead Carbonell, where several mock buildings were demolished in the market place for the film. Hook Norton brewery served as the Handyman brewery where Blott obtains copious supplies of strong ale for the motorway workers. It was a drunk, played by Jimmy Nail, who 'demolished' Guilstead Carbonell.", R.drawable.hours_rule_cover),
        arrayOf("Lifedtyle Builder", "Tom & Ariana Sylvester", "2018", "Little Hangleton is a fictional Muggle village notable as the place of origin of Voldemort's maternal and paternal ancestors, and as the place where he was restored to bodily form in Harry Potter and the Goblet of Fire. Although the village first appears in Goblet of Fire, the fourth volume in the series, it is not described until Harry Potter and the Half-Blood Prince, the sixth volume. The village occupies the floor of a valley, bounded by steep hills, not far from the larger settlement of Great Hangleton. Above the village on one side of the valley are a church, a cemetery and the Riddle House, the former estate of the aristocratic Riddle family and at one time the finest house in the village. It first appears in the opening of Goblet of Fire as the location of Frank Bryce's murder; and at this point in the chronology of the Harry Potter series, it is decrepit and covered in vines. It is believed to be held by a rich man for tax purposes, although this is in reality to keep it from being sold or torn down.", R.drawable.lifestyle_builder_cover),
        arrayOf("Minimalist Marketing", "Joe Fontenot", "2019", "The name of the street refers to the hedges that enclose many suburban gardens, as Rowling liked the idea of enclosure. In the novels and films, the Dursleys' home is in a respectable and boring neighbourhood where the neighbours ostracise Harry, who despises Little Whinging because of his memories of his cruel treatment there. Arabella Figg, who lives two streets away from 4 Privet Drive in the novels (but just across the road in the films) knows of Harry's magic, because she is a Squib member of the Order of the Phoenix, placed in Little Whinging by Dumbledore to keep an eye on Harry. In Harry Potter and the Order of the Phoenix, Dumbledore reveals that the reason Harry must return there at least once a year is because of the protection Harry's mother left upon him when she gave her life to save him. That act allowed an ancient magic to work, which meant Harry could never be harmed as long as he lived in the care of his mother's blood; in this case, his Aunt Petunia. This charm would not expire until Harry turned 17.", R.drawable.minimalist_marketing_cover),
        arrayOf("The Queen of Ocean", "Teijin", "2020", "Filming for Privet Drive in Harry Potter and the Philosopher’s Stone took place in a real urban area, 12 Picket Post Close, Bracknell in Berkshire, located 25 miles (40 km) west of London.[10][11] For all the subsequent film's scenes set in Privet Drive, filming took place on a constructed set in Leavesden Film Studios (replicating 12 Picket Post Close), which proved to be cheaper than filming on location.[12] This standing set, which remained in use throughout the decade-long filming history of the Harry Potter films, remains visible in Google Maps aerial views of the studio. It sits in a location with other Harry Potter sets and props.", R.drawable.queen_ocean_cover),
        arrayOf("The Rebel's", "Scott Mariani", "2020", "In the Chamber of Secrets, Draco reveals that the manor has its own chamber of secrets under the drawing room, which was used to hide valuable dark artefacts when the Ministry raided the manor. Voldemort used Malfoy Manor as headquarters on at least one occasion in Deathly Hallows. The three Malfoys seemed quite displeased by this use of their manor as Voldemort himself noted; only Bellatrix appears to be pleased he is there. The Malfoys have become prisoners in their own home and are in very real fear for their lives. During the Deathly Hallows, several prisoners are being kept in the basement on Voldemort's orders, including Luna Lovegood, Dean Thomas, Griphook the Goblin, and Mr. Ollivander. When Snatchers capture Harry, Ron, and Hermione, they are brought to Malfoy Manor. They escape with the other prisoners thanks to Dobby's help. The four residents of the manor are then placed under house arrest by Lord Voldemort, until they join with other Death Eaters in the Battle of Hogwarts.", R.drawable.rebels_revenge_cover),
        arrayOf("Wings of Love", "Nancy Rivard", "2019", "Many security measures are in place at Grimmauld Place: there are anti-apparation charms, the place is Unplottable, the whole house is under a Fidelius charm and it is disguised from Muggles and other interlopers. In the seventh book, it is noted that the neighbours had long ago come to terms with the houses on their square running straight from 11 to 13. It is as secure as any magical dwelling can be and can accommodate a large number of people. For this reason, it was chosen as the headquarters of the reconstituted Order of the Phoenix when Sirius offered it to the Order. Only magical people can see it, and only if told the location by the Secret Keeper himself. The house is even immune from the 'Taboo' imposed by the Ministry of Magic after the coup d'état. This is known because Hermione Granger mentions Voldemort by name at least once whilst inside the house.", R.drawable.wings_love_cover),
        arrayOf("Confident Journey", "Ron Kelemen", "2010", "The Durmstrang Institute for Magical Learning (German: Durmstrang-Institut für Zauberei) is a magic school that makes its first appearance in Goblet of Fire. The school has existed for at least 700 years, when they began participating in the Triwizard Tournament. Dumbledore welcomes Durmstrang's students as our friends from the North, and J. K. Rowling is said to have located the school somewhere in Northern Scandinavia. Durmstrang students wear heavy furs with blood-red robes. The students of Durmstrang mentioned by name are Russians and Bulgarians. Durmstrang is portrayed as an all-boys school in the film, but according to the book, it is co-ed.[22] Several female students are mentioned, though not by name.", R.drawable.confident_journey_cover),
    )

    val listBook: ArrayList<Book>
        get() {
            val list = arrayListOf<Book>()
            for (data in dataBooks) {
                val book = Book()
                book.bookTitle = data[0].toString()
                book.bookAuthor = data[1].toString()
                book.bookPublishYear = data[2].toString()
                book.bookSynopsis = data[3].toString()
                book.bookCover = Integer.valueOf(data[4].toString())
                list.add(book)
            }
            return list
        }

}